import Head from "next/head";
import Post from "../components/Post";

export default function Home() {
	return (
		<div className="container">
			<Head>
				<title>Social | Home</title>
				<meta
					name="Social home page"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Post />
			</main>

			<footer></footer>
		</div>
	);
}
