import Head from "next/head";
import Post from "@components/Post";

export default function Home() {
	return (
		<>
			<Head>
				<title>Social | Home</title>
				<meta
					name="Social home page"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container">
				<Post />
			</main>

			<footer></footer>
		</>
	);
}
