import Head from "next/head";
import PostList from "@components/PostList";
import { GetStaticProps } from "next";
import { getItemList } from "./api/api";
import { IPost } from "@interfaces/post.interface";

export default function Home({ posts }: { posts: IPost[] }) {
	return (
		<>
			<Head>
				<title>Social | Home</title>
				<meta
					name="Social home page"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container">
				<PostList posts={posts} />
			</main>

			<footer></footer>
		</>
	);
}

export const getStaticProps: GetStaticProps = async () => {
	const posts = await getItemList("posts");
	console.log(posts);
	return { props: { posts } };
};
